app = 'dai-viet-chien-server'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[[services]]
  internal_port = 8080
  protocol = 'tcp'

  [[services.ports]]
    handlers = ['http']
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ['tls', 'http']
    port = 443

  [services.http_checks]
    interval = 30000
    timeout = 5000
    path = '/health'
